Newsletter changes
HACManchester/membership-system pull request #120
Opened 2022-12-01 20:13 UTC by rjackson

After a chat with Joe about our newsletter and some desired changes to the membership system, I've put together this PR with the following changes:

- Remove newsletter checkbox from registration pages.
- Opt new registrations into newsletter emails by default
  - Under legitimate interest justification as we have an obligation to keep members of the space aware of news, announcements, and member meetings
  - If members are _really_ not interested in emails, we retain the newsletter checkbox on the edit account page to provide an opt-out mechanism
- Create a new "Newsletters" page
  - Accessible to admins only
  - Listing all e-mail addresses of newsletter recipients
  - Listing all e-mail addresses of active members

Whilst the membership system had a `/newsletters` endpoint with a JSON feed of newsletter opt-ins, the actual newsletter recipients were being retrieved by querying the database directly. We have repurposed that endpoint for the "newsletters" page, and updated its underlying conditions to include active or recently lapsed (within the last 6 months) members.

Screenshot of the new newsletters page:

![Screenshot 2022-12-01 at 20 01 08](https://user-images.githubusercontent.com/602850/205149651-6abd33cf-50bb-4cb3-b998-3f970e8bd9cc.png)

cc @josephxtian – as I can't seem to add you as a reviewer 😢

2022-12-01 21:45 UTC, conorriches approved these changes
Great stuff!

2022-12-01 22:01 UTC, chris18890 commented on resources/views/account/edit.blade.php
> +            {!! Form::label('newsletter', 'Opt in to membership newsletters', ['class'=>'']) !!}
Should this be saying "Opt in" if members are already opted in?

2022-12-01 22:01 UTC, chris18890 requested changes
Should this be saying "Opt in" if members are already opted in?

2022-12-02 11:09 UTC, rjackson commented on resources/views/account/edit.blade.php
> +            {!! Form::label('newsletter', 'Opt in to membership newsletters', ['class'=>'']) !!}
I _think_ it still worked in context, but yeah there are tweaks I want to explore to make this clearer to members.

I've been playing around. What do we think of the following?

![image](https://user-images.githubusercontent.com/602850/205279459-ac6c3b0b-870d-462d-97d1-11ded907c8fc.png)

2022-12-02 11:10 UTC, chris18890 commented on resources/views/account/edit.blade.php
> +            {!! Form::label('newsletter', 'Opt in to membership newsletters', ['class'=>'']) !!}
Looks decent!

2022-12-02 11:42 UTC, josephxtian commented
Could we change this to
Newsletters will be sent out periodically to keep you up to date with
announcements, news and events relevant to your membership of the space.

Just because the newsletter isn't quarterly, and by not defining the period
we never need to change the text again.

Cheers :)

On Fri, 2 Dec 2022, 11:09 Rob Jackson, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In resources/views/account/edit.blade.php
> <https://github.com/HACManchester/membership-system/pull/120#discussion_r1038035791>
> :
>
> >  <div class="row">
>      <div class="col-xs-12 col-md-8">
>          <div class="form-group {{ Notification::hasErrorDetail('newsletter', 'has-error has-feedback') }}">
>              {!! Form::checkbox('newsletter', true, null, ['class'=>'']) !!}
> -            {!! Form::label('newsletter', 'Opt in to occasional newsletters', ['class'=>'']) !!}
> +            {!! Form::label('newsletter', 'Opt in to membership newsletters', ['class'=>'']) !!}
>
> I *think* it still worked in context, but yeah there are tweaks I want to
> explore to make this clearer to members.
>
> I've been playing around. What do we think of the following?
>
> [image: image]
> <https://user-images.githubusercontent.com/602850/205279459-ac6c3b0b-870d-462d-97d1-11ded907c8fc.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HACManchester/membership-system/pull/120#discussion_r1038035791>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRQ3XNZ3U7YP5HOH4VJEDTWLHKFPANCNFSM6AAAAAASRFSGJI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-03 02:15 UTC, chris18890 approved these changes

2022-12-03 16:04 UTC, merged