Allows equipment team to edit tools
HACManchester/membership-system pull request #153
Opened 2024-02-12 11:37 UTC by diazwatson

After my previous PR and once admin added me to the equipment team I was able to create the welding machine on the welding are BUT I cannot fully edit it as only admins or trainers can do.

This PR solves the issue by allowing members of the equipment team to fully edit tools.

## Other changes
- Adds Protective clothing to the list of PPE
- Adds [Warden](https://warden.dev/) .env sample for devs using it
- The link in "please contact someone on the equipment team" now also works in local envs
- Bit of cleaning

2024-02-12 11:52 UTC, harvy4002 commented
Cool. This is what I asked for a long time ago and I had to be made admin instead. I don't know much about the underlying code base do you get a +1 for feature but I can't code approve it.

2024-02-12 12:26 UTC, rjackson requested changes
I think the biggest change here is fixing `$isTrainerOrAdmin` determining what fields an equipment maintainer can change?

Members of relevant equipment teams should already have permission to update via EquipmentPolicy:

https://github.com/HACManchester/membership-system/blob/c244c540a0b84bec04be5bcf7cd2a1a0ec35cef4/app/Policies/EquipmentPolicy.php#L53-L56

I've dropped a few comments below, because some of the changes you've added I don't think will do what you expect, and I think they'll break the equipment pages for users without any particular permissions.

If possible, I'd recommend avoiding having your editor (I assume) auto format / auto adjust imports. With an messy codebase like ours these changes add a lot of noise and its hard to tell which changes here are actually functional or purely decorative.

If you do need to do some mass formating of a file, or many files, it'd be helpful to do so on a separate commit ([we can then also make a `git-blame-ignore-revs` file to skip it when checking file history](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view))

2024-02-12 12:26 UTC, rjackson commented on resources/views/equipment/index.blade.php
> +        the <a href="<?=URL::to('/')?>/groups/equipment">equipment</a> team
We can use route helpers to generate links, rather than having to hard code url structures.

Also we shouldn't need to use short echo tags or raw PHP in these templates, check out docs on [Blade templating](https://laravel.com/docs/5.3/blade).

```suggestion
        the <a href="{{ routes('groups.show', 'equipment' }}">equipment</a> team
```

(untested)

2024-02-12 12:26 UTC, rjackson commented on .env.warden
> +APP_KEY=base64:Q+XXtB5dsJcoodRVZxyF/f+nWDknjI4kCHxQS2xkbxY=
Best avoiding committing secrets to the repository, even if they're only for development environments. Better to have people generate their own via `php artisan key:generate`.

```suggestion
APP_KEY=
```

2024-02-12 15:08 UTC, diazwatson commented on resources/views/equipment/index.blade.php
> +        the <a href="<?=URL::to('/')?>/groups/equipment">equipment</a> team
tested and works fine

2024-02-12 15:12 UTC, diazwatson commented on app/Http/Controllers/EquipmentController.php
> +        return Redirect::route('equipment.edit', $equipment->toArray());
The reason for this was because I noticed that route expects the second parameter to be an array and instead we are passing the equipment object.
![Screenshot 2024-02-12 at 14 32 47](https://github.com/HACManchester/membership-system/assets/1080386/52014e18-00e3-4f6a-a19e-372086475002)

Anyway I have reverted this change for now doesn't really affect the purpose of this PR.

2024-02-12 15:21 UTC, diazwatson commented
@rjackson you were right, the changes in lines 140 and/or 148 breaks the equipment page for users without privileges:

```
        return \View::make('equipment.show')
            ->with('equipmentId', $equipmentId)  <!--- replacing this undefined variable with the actual equipmentId, breaks the equipment page
            ->with('equipment', $equipment)
            ->with('trainers', $trainers)
            ->with('equipmentLog', $equipmentLog)
            ->with('userInduction', $userInduction)
            ->with('trainedUsers', $trainedUsers)
            ->with('usersPendingInduction', $usersPendingInduction)
            ->with('usageTimes', $usageTimes)
            ->with('user', $user) <!--- replacing this undefined variable with the actual user object, breaks the equipment page
            ->with('isTrainerOrAdmin', $isTrainerOrAdmin)
            ->with('memberList', $memberList)
            ->with('docs', $docs)
            ->with('now', $now);
```
I have reverted these changes

2024-02-12 15:35 UTC, diazwatson commented
Regarding the `isTrainerOrAdmin` functionality and from the user point of view it is a bit weird.

Look at my case:

I have made all these changes to be able to load the tools in the new welding area for members to be able to use.

I am the area coordinator (doesn't make any difference in the members system), member of the welding team, member of the equipment team and still...

...I cannot edit the information of the welding machine because only admins and trainers of this tool can do.

2024-02-12 15:38 UTC, diazwatson commented on app/Http/Controllers/EquipmentController.php
> +        return Redirect::route('equipment.show', $equipment->toArray());
change reverted

2024-02-12 15:45 UTC, rjackson commented
>Regarding the isTrainerOrAdmin functionality and from the user point of view it is a bit weird.

Hmm, yeah we can probably get rid of that and just allow editing of all fields now.

The history is that any member could edit some parts of equipment pages, but with the introduction of teams and/or area coordinators that felt a bit overly permissive and I'd changed it so only admins, the generic "equipment" group, or equipment-specific groups could edit pages (this is where the EquipmentPolicy file came from): b8198f2c592fc5f2088fa8ce4c153eaaf4279d7f

Now that only admins and equipment maintainers can edit pages (trainers no longer have permission), there's no value in this `isTrainerOrAdmin` distinction. I'd be happy if you rip it all out any allow editing of all fields.

2024-02-12 15:50 UTC, rjackson commented on app/Http/Controllers/EquipmentController.php
> +        return Redirect::route('equipment.edit', $equipment->toArray());
Ah, the documented function signature there is probably wrong. Laravel's quite permissive with how it takes route parameters, and is quite happy taking a single object instead of an array here.

The actual implementation allows any input, but defaults to an empty array:

https://github.com/laravel/framework/blob/2906b572aa83ff46b8ad57093dd0e859c0ff783f/src/Illuminate/Routing/Redirector.php#L156

Further down the call stack if `$parameters` is an object (or rather, is not an array) its wrapped with an array.

https://github.com/laravel/framework/blob/2906b572aa83ff46b8ad57093dd0e859c0ff783f/src/Illuminate/Routing/UrlGenerator.php#L436

2024-02-15 13:08 UTC, rjackson commented
Sorry for being slow on this! I've had a glance over the changes, but haven't had a chance to test them yet.

Happy to approve & merge if anybody else is able to test & write up behaviour for:

- Unprivileged members
    - Can view equipment pages
    - Can request training
- Trainers
    - Can mark people as trained
    - Can unmark people as trained
    - Can mark people as trainers
    - Can unmark people as trainers
- "Equipment" team
    - Edit the equipment page
    - Delete the equipment page
- Tool-specific team (e.g. "Metalworking")
    - Edit the equipment page
    - Delete the equipment page
- Admins
    - Edit the equipment page
    - Delete the equipment page

2024-02-15 14:13 UTC, diazwatson commented
Out of curiosity, do we have an staging env to test this project?

2024-02-15 14:19 UTC, chris18890 commented
> Sorry for being slow on this! I've had a glance over the changes, but haven't had a chance to test them yet.
> 
> Happy to approve & merge if anybody else is able to test & write up behaviour for:
> 
>     * Unprivileged members
>       
>       * Can view equipment pages
>       * Can request training
> 
>     * Trainers
>       
>       * Can mark people as trained
>       * Can unmark people as trained
>       * Can mark people as trainers
>       * Can unmark people as trainers
> 
>     * "Equipment" team
>       
>       * Edit the equipment page
>       * Delete the equipment page
> 
>     * Tool-specific team (e.g. "Metalworking")
>       
>       * Edit the equipment page
>       * Delete the equipment page
> 
>     * Admins
>       
>       * Edit the equipment page
>       * Delete the equipment page

Is the idea that the Trainers _may_ also be part of the "equipment" team or a tool-specific team, but that they're not dependant on each other?

2024-02-15 14:20 UTC, chris18890 commented
> Out of curiosity, do we have an staging env to test this project?

We do, it just also happens to tbe the Production env ;)

2024-02-16 23:51 UTC, diazwatson commented
Maybe @conorriches can help with the test part of this?

2024-02-19 00:43 UTC, rjackson approved these changes

2024-02-19 00:43 UTC, merged