require keyfob before allowing access code
HACManchester/membership-system pull request #70
Opened 2022-10-12 15:27 UTC by conorriches

At a recent members meeting it was decided to not allow freshly joined members to setup a keycode, so that they had to interact with someone to set up a fob which acts as some sort of induction.

This change:
* Requires users to have completed the general induction online before they set up an access method
* Requires users to set up a keyfob first, by not allowing someone to setup a keycode until there's already an existing method

Caveats:
* If you're a long standing member and delete all your access methods, you will need to add a fob first
* This can be overridden by entering any old rubbish into the keyfob field, as we don't validate the ID entered. We could do a check for a valid looking pattern (hex characters only) but even then we can't know if an entered ID is garbage.
* This is a nudge and not intended to be foolproof.

2022-10-12 17:02 UTC, rjackson approved these changes
Looks good to me!

I've dropped some comments below, 2 of which are side-comments relating to general housekeeping tasks that I'm interested in looking into – these have absolutely no bearing on the current work.

2022-10-12 18:26 UTC, conorriches commented on app/Http/Controllers/KeyFobController.php
> +        if(\Auth::user()->online_only || !\Auth::user()->induction_completed){
Thanks for sharing that - policies look so awesome!

2022-10-12 18:28 UTC, conorriches commented on app/Http/Controllers/KeyFobController.php
> +            if(\Auth::user()->keyFobs()->count() == 0){
So we buy fobs in bulk from eBay, and put them in a tub. Therefore we don't have any record of a valid fob - members are welcome to use their existing fobs/bus passes too so all we can do here is check its hex and not too short or too long... Not actually sure what the minimum and maximum length of a fob is though... I'll check

2022-10-12 21:13 UTC, conorriches commented on resources/views/account/edit.blade.php
> +            {!! Form::hidden('user_id', $user->id) !!}
Great spot - I hadn't spotted this before. I've tested the issue and it needed to go, so I've done it in this PR too.

2022-10-12 21:26 UTC, conorriches commented on resources/views/account/edit.blade.php
> +            {!! Form::hidden('user_id', $user->id) !!}
I'd guess this was added so that admins can add fobs to other peoples accounts, but I don't think we've ever done this, so it's going.

2022-10-13 08:12 UTC, rjackson requested changes

2022-10-13 08:12 UTC, rjackson commented on app/Http/Controllers/KeyFobController.php
>          $fob->markLost();
`$fob` will be an instance of `Illuminate\Database\Query\Builder` by line 94, so the `markLost` call will fail.

Also worth bringing back `firstOrFail` so we return a HTTP 404 if given an invalid key fob ID, otherwise we'll probably get a PHP fatal error "Call to a member function markLost() on null".

```suggestion
        $fobQuery = KeyFob::where('id', $id);

        if(!\Auth::user()->isAdmin()){
            $fobQuery->where('user_id', \Auth::user()->id);
        }
        $fob = $fobQuery->firstOrFail();
        $fob->markLost();
```

2022-10-13 08:29 UTC, rjackson commented on app/Http/Controllers/KeyFobController.php
> +            if(\Auth::user()->keyFobs()->count() == 0){
Got it. Do we know the board's appetite for this risk? If they're happy to accept it, then no problem.

If not, we might have to discuss wider-ranging changes within & beyond the system to guard against potential unauthorised access. Perhaps something along the lines of an approval system for unrecognised fob registrations, but space-provisioned fobs are pre-approved?

That will require somebody to register the big tub of fobs that come in from eBay though :P

2022-10-13 16:20 UTC, rjackson commented on app/Http/Controllers/KeyFobController.php
> +            if(\Auth::user()->keyFobs()->count() == 0){
Actually reflecting on this a bit more, a "fob" is the wrong subject in such an approval/pre-approval process. It's actually the "user" that we care about.

May be wider conversations to have about the induction process and either a post-induction admin process of approving the member accounts of those who attended, or giving them some _thing_ that proves they attended an induction that they can add to the system (an unique induction code, a pre-approved keyfob, ...)

Definitely feels like a topic to explore separately to this PR.

2022-10-13 20:50 UTC, conorriches commented on app/Http/Controllers/KeyFobController.php
>          $fob->markLost();
great suggestion 👍

2022-10-13 20:52 UTC, conorriches commented on app/Http/Controllers/KeyFobController.php
> +            if(\Auth::user()->keyFobs()->count() == 0){
I know when we've had discussions about fob ID cloning and so on before, we usually realise that if someone is trying that cleverly to get into the space, they probably belong on the inside, and if they wanted to loot us, they'd sign up under a false name, act nice for first meet, then disappear :p

2022-10-13 20:53 UTC, conorriches commented on app/Http/Controllers/KeyFobController.php
> +            if(\Auth::user()->keyFobs()->count() == 0){
so yeah, definitely one to discuss with folk who will be doing the general induction. I'm personally cool with any member being able to mark any other member as inducted for the general space induction, as we are basically built on trust

2022-10-14 09:15 UTC, rjackson approved these changes

2022-10-14 11:40 UTC, merged